language: node_js
node_js:
  - "6"
  - "6.2"
  - "6.1"
  - "6.0"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
after_success:
  - bash <(curl -s https://codecov.io/bash)
